### ISSUE TITLE
Some parameters have changed from prev version

### ISSUE THREAD

**Issue by ajuancer** [JeffLIrion/adb_shell#126]
Hi there!
I had a piece of code that looked like this:
```python
device.pull(some_path, dest_file=another_path)
```
And just want to know if the `adb_shell` version I was using was the previous, v0.2.1

(there is no real issue, I have just updated to the new version, and updated the code to:
```python
 device.pull(some_path, another_path)
```
)

Another changed I have done is removing the `default_timeout_s` parameter in `AdbDeviceTcp`, because, althought it continues in [the documentation](https://adb-shell.readthedocs.io/en/stable/adb_shell.adb_device.html?highlight=devicetcp#adb_shell.adb_device.AdbDeviceTcp), i got the `Unexpected argument` warning with:
```python
device = AdbDeviceTcp(remote_ip, 5555, default_timeout_s=16.)
```
(that now I have updated to:
```python
device = AdbDeviceTcp(remote_ip, 5555)
```
)
Thanks in advance 😄

**Comment by JeffLIrion** [comment]
You can always compare releases like this: https://github.com/JeffLIrion/adb_shell/compare/v0.2.1..v0.2.2

Also, the documentation that you linked says `default_transport_timeout_s`.

**Comment by ajuancer** [comment]
that was a fast response! 🏎️🏎️ 
thanks, jeff!
