### ISSUE TITLE
[LOGS NEEDED!] Fix support for newer devices

### ISSUE THREAD

**Issue by JeffLIrion** [JeffLIrion/adb_shell#15]
Currently, this package won't work well for newer devices. In order to figure out what the problem is and fix it, I need logs. Here is how to collect them, depending on how you're using this package. 

## 1. Standalone package

Set the log level to debug via

```python
import logging

logging.getLogger("adb_shell").setLevel(logging.DEBUG)
```

## 2. Home Assistant Android TV integration (HA 0.99 and below)

Use this [androidtv custom component](https://github.com/JeffLIrion/ha-androidtv) (HACS compatible) and follow the [Python ADB implementation](https://www.home-assistant.io/components/androidtv#2-python-adb-implementation) instructions. Enable debug logging via the `logger.set_level` service with the parameters:

```json
{"custom_components.androidtv.androidtv.adb_shell": "debug"}
```

When the device is on, it should constantly connect and then become unavailable. Once you have logs of this occurring, you can set the log level back to warning, error, etc.

## 3. Home Assistant Android TV integration (HA 0.100 and above)

This is similar to the instructions above, except that you'll use the built-in Android TV integration and the `logging.set_level` service parameters are:

```json
{"adb_shell": "debug"}
```

**Comment by mattsch** [comment]
Logs from a 2015 Nvidia Shield running the latest hotfix firmware `8.0.1(32.5.20575)`
[adb-shell-debug.log](https://github.com/JeffLIrion/adb_shell/files/3673784/adb-shell-debug.log)

**Comment by JeffLIrion** [comment]
Closed by https://github.com/JeffLIrion/adb_shell/pull/14
