### ISSUE TITLE
How do you find the path to android ADB rsa key?

### ISSUE THREAD

**Issue by alexbgameson** [JeffLIrion/adb_shell#151]
How do you know the path to android ADB rsa key?

**Comment by jvmk** [comment]
They are placed under `~/.android/` by default IIRC.

**Comment by JeffLIrion** [comment]
> They are placed under `~/.android/` by default IIRC.

Yep. 

You can also generate a key if you don't have one already. 

```python3
from adb_shell.auth.keygen import keygen

keygen("/some/directory/adbkey")
```
