### ISSUE TITLE
Is it possible to support multiple streams?

### ISSUE THREAD

**Issue by Suwolia** [JeffLIrion/adb_shell#163]
hi, is it possible to support multiple streams? I noticed that "We don't support multiple streams..." in adb_shell.adb_device.py[row: 922].

**Comment by JeffLIrion** [comment]
It should be possible, but it's complicated. I don't plan to add that functionality, but if someone wants to contribute it, that would certainly be welcome.

**Comment by Suwolia** [comment]
okay, tks
