### ISSUE TITLE
Some Features Implementation

### ISSUE THREAD

**Issue by enty8080** [JeffLIrion/adb_shell#187]
Hello `adb_shell` developers,

* **1.** Interactive shell.

I would like to ask about adding interactive shell to adb_shell project. I think it will be good for people who does not want to send commands manually through `device.shell()`.

```python3
device.interact()
```

**result:**

```
android@localhost # pwd
/sdcard
android@localhost #
```

* **2.** Ability to install/uninstall `.apk` files on devices.

```python3
device.install('/path/to/apk')
# device.uninstall('bundle identifier')
```

* **3.** Reboot device.

```python3
device.reboot()
```

Regards,
Ivan Nikolsky (@enty8080)

**P.S.** I am using your python package and it is very good **:)**, so it will be good to see this features.

**Comment by JeffLIrion** [comment]
1. Wouldn't that just be a wrapper around `shell()` calls?
   ```python
   while True:
       command = input("adb # ")
       if command == "exit":
           break
       resp = device.shell(command)
       if resp:
           print(resp)
   ```
2. Those are just shell commands. The install command is ([link](https://gist.github.com/mcfrojd/9e6875e1db5c089b1e3ddeb7dba0f304#install-apps-on-your-android-device-from-home-assistant)): `pm install -r /sdcard/Download/something.apk`
3. I think that's just `device.shell("reboot")`.

**Comment by enty8080** [comment]
**1.** Okay, I think it’s good.

**2.** Okay, I read about it.

**3.** No, reboot is not a shell command:

https://github.com/google/python-adb/blob/f4e597fe55900651a8a91fccc1e09061fd96b5e9/adb/adb_commands.py#L345

**Comment by JeffLIrion** [comment]
This should accomplish reboot:

```python
device._open(b'reboot:', transport_timeout_s, read_timeout_s, timeout_s)
```

**Comment by enty8080** [comment]
@JeffLIrion Sorry for late response. Yes, it works fine for me, thank you.

**Comment by JeffLIrion** [comment]
OK, I'll merge the corresponding pull request. 

I don't intend to implement items 1 and 2, as the scope of this package is to implement the ADB protocol, not to provide utilities and helper functions. I don't want to clutter the `AdbDevice` and `AdbDeviceAsync` classes. That said, I think the following approach would be reasonable, if you'd like to contribute it. 

1. Implement an `AdbDeviceUtils` class that looks like:
   ```python
   class AdbDeviceUtils:
       def __init__(self, adb_device):
           self._adb_device = adb_device

       def install(self, apk, ...):
           self._adb_device.shell("<install command>", ...)
   ```
2. Add a property to the `AdbDevice` class:
   ```python
   @property
   def utils(self):
       return AdbDeviceUtils(self)
   ```

Then you could do `device.utils.install(...)`. 

And do the same for the `AdbDeviceAsync` class.

**Comment by PwnPeter** [comment]
Hello, I up the subject in regards to the installation functionality.

It would be useful to add the command "adb install" which allows to specify a path to an apk on the host machine and not on the android phone.
