### ISSUE TITLE
Using pull on BytesIO object

### ISSUE THREAD

**Issue by JartanFTW** [JeffLIrion/adb_shell#202]
Due to this programs complexity, I'm struggling to subclass to use pull onto a BytesIO object rather than an actual file on my machine.

Is there any sort of implemented way I can do this that I'm missing in my reading of the docs?

**Comment by JeffLIrion** [comment]
That's not supported, but you should be able to pretty much copy & paste these lines: https://github.com/JeffLIrion/adb_shell/blob/ba3fb4b9e7acfb6e9b8851bed65d5bb4c3b20733/adb_shell/adb_device.py#L913-L919

**Comment by JartanFTW** [comment]
Got it working, thanks for the assistance.
