### ISSUE TITLE
How can I determine which devices are available to connect to?

### ISSUE THREAD

**Issue by geajack** [JeffLIrion/adb_shell#37]
In the example code in the readme, we find the line

```
device1 = AdbDevice(serial='192.168.0.111:5555', default_timeout_s=9.)
```

This seems to suggest that in order to use this library to talk to a device, I need to know its IP and port already. Is there a facility in this library to obtain this information? If not, I'd suggest there should be.

**Comment by JeffLIrion** [comment]
I'm assuming that you know the IP address of the device. There is no discovery tool in this package, but contributions are welcome.

**Comment by geajack** [comment]
@JeffLIrion Thanks for the quick response. Would you be able to point me in the direction of figuring out that IP? I'm not sure what to google, "adb device IP" doesn't seem to turn up any useful results, and of course when I connect with the standard ADB CLI I just use the device's serial number.

**Comment by JeffLIrion** [comment]
The simplest way to get the IP address is to log into you router and view the list of connected devices. 

Connecting over USB is not supported in this package. If you want to add support for that, it would be welcome. You'd need to create a `usb_handle.py` file that mirrors the `tcp_handle.py` file and allow for using that in `adb_device.py`.

**Comment by ubaierbhat** [comment]
I am just trying library as well and I was going to ask the same question. Limiting to tcp connection doesn't sound nice and there should be a way to get a list of connected devices as well. 

**This is how I make it work:**

You can get the ip address of the device from `Settings > About Phone > Status` on your phone. Or as Jeff said you can check your router.  Or if you are already connected with usb 
`adb shell ip route | awk '{print $9}''` 

But having just an ip address of your device won't be enough. You **must** enable adb connection over tcp first. For this your device needs to be connected with usb and use following adb command:
`adb tcpip [port]` e.g. `adb tcpip 5555`

`AdbDevice(serial='192.168.0.111:5555').connect()` is equal to `adb connect 192.168.0.111:5555`

So the not recommended (as it uses adb commands directly) way to do it will be
```python3
import os
from pathlib import Path

from adb_shell.adb_device import AdbDevice
from adb_shell.auth.sign_pythonrsa import PythonRSASigner

# get ip (WLAN only) address of device
ip = str(os.popen("adb shell ip route | awk '{print $9}'").read()).strip()
print(f'IP address: {ip}  ')

# Enable adb over tcp
port = '5555'
os.system(f'adb tcpip {port}')

# Connect (authentication required)
home = str(Path.home())
with open(f'{home}/.android/adbkey') as f:
    priv = f.read()

signer = PythonRSASigner('', priv)
device = AdbDevice(serial=f'{ip}:{port}')
device.connect(rsa_keys=[signer], auth_timeout_s=0.1)

# Send a shell command
response = device.shell('echo hello')
print(response)

```

**Comment by JeffLIrion** [comment]
I wrote this package to implement ADB shell functionality over TCP.  If someone wants to implement that same functionality over USB, including writing tests with complete coverage, then that would be a welcome contribution.  But I have no plans to do that myself.

**Comment by JeffLIrion** [comment]
@ubaierbhat in your commands above, would you need to close the USB connection before connecting over TCP?

**Comment by geajack** [comment]
Thanks for resolving my confusion. In the end I actually found [ppadb](https://github.com/Swind/pure-python-adb) is a better fit for my use case.

**Comment by ubaierbhat** [comment]
@JeffLIrion no you don't need to close the usb connection.
