### ISSUE TITLE
License and Copyright issue.

### ISSUE THREAD

**Issue by matthieuxyz** [JeffLIrion/adb_shell#38]
# Abstract

Hello,

We are considering the idea to use adb_shell as a replacement for python-adb in our project, but I believe that adb_shell is in copyright and license infringement towards python-adb. This can be solved on our side, when adding adb_shell to our project, but it would be even better to do it on your side (for you and your future users).

Disclaimer: I am not a legal expert. I am just applying the license as I understand them and following other well-known projects' practices. My interpretation could be wrong.

# License infringement: Apache license copy

## Problem:

In the Apache license, point 4. (a):

> You must give any other recipients of the Work or Derivative Works a copy of this License;

The repository contains code from python-adb (licensed under apache) and does not include a full copy of the apache license.

## Solution:

Add a full copy of the apache license at the root of the project. Can be appended to the LICENSE file or a separate file, doesn't matter.

Exemple: https://github.com/renpy/renios/blob/5f01ce1bbb94c04193bf1bbcfb941c4d8563a98b/LICENSE.md

OR

Get an authorization from Google to re-license everything under MIT

# Copyright infringement: missing google copyright notice

## Problem

In the Apache license, point 4. (b):

> You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works;

Unmodified files still includes the google copyright notice (ie: sign_cryptography.py) which is nice.

There is no obligation for files that only contains new works.

But files that includes both new and old works does not include a google copyright notice (ie: adb_device.py).

## Solution

In files that includes work from python-adb:

* Add the original copyright notice and license from python-adb

* Add a new copyright notice or anything that could indicate that the file was modified

* Possibly add an additional copyright statement and a license header for the additional work

exemple: https://github.com/LibreOffice/core/blob/master/TEMPLATE.SOURCECODE.HEADER

# License infringment: Apache to MIT re-license

## Problem

This repository includes work covered by MIT license and work covered by Apache license.
Some files includes work covered by MIT and work covered by Apache

The apache license has more restrictions than MIT:

> You must cause any modified files to carry prominent notices stating that You changed the files; 

And:

> Trademarks. This License does not grant permission to use the trade names, trademarks, service marks, or product names of the Licensor, except as required for reasonable and customary use in describing the origin of the Work and reproducing the content of the NOTICE file.

As a result a joint-work under Apache and MIT licenses − And his is probably the only point where I am 100% sure − can be automatically re-licensed under Apache, but cannot be re-licensed under MIT without the copyright holder's consent.

As a result: a file containing joint-work cannot be under MIT and the repository as a whole cannot be under MIT.

## Solution

License everything under Apache

OR

Get an authorization from Google to re-license everything under MIT

OR

License the additional files under MIT and license the files that contains joint-work under Apache.
The repository would then contains files under different licenses or the repository as a whole could be under Apache.

OR

License old work under Apache and additional work under MIT even for joint-work in the same file. The joint-work will have part of its code under MIT and parts of his code under Apache. The repository as a whole could be under Apache or under both licenses.

Even if the repository is under Apache, any file or line of code that is under MIT, would still be usable under MIT if separated from the Apache code:
* *if* we remove every line of code from google, the file/repository could be under MIT again.
* *if* we copy some lines of code that only include additional work it could be under MIT as well.

# Improvement: add contributors to copyright notice

## Problem

This is probably not the most important change, but the copyright notice in the LICENSE file is:

> Copyright (c) 2019 Jeff Irion

And the project does not include a Contributor License Agreement.

So the copyright holder for any line of code is the person that wrote that line. And the copyright holder for all the additional work (excluding google's work) is probably something like "Jeff Irion and contributor 1 and contributor 2 and ...". But since the contribution can be tracked by git, I don't think there is any infringement, it just more conventional to include contributors in the copyright notice. You can also list all contributors by name in the copyright notice or a separate file, but it's completely optional.

## Solution

Change copyright notice to:

> Copyright (c) 2019 Jeff Irion and contributors

OR

Add a Contributor License Agreement

**Comment by JeffLIrion** [comment]
Thanks for the detailed info!  I took your suggestions into account and created this pull request: https://github.com/JeffLIrion/adb_shell/pull/39

If you have any feedback, please let me know.  

Also, if you're willing to share, I'd be interested in learning about what you're using this package for.

**Comment by matthieuxyz** [comment]
Perfect! Thanks for the quick response.

There is nothing done yet (we are still using a patched version of python-adb), but it would be used for a proprietary malware analysis platform, we need adb to install suspicious apk on an android emulator and read logs.

**Comment by JeffLIrion** [comment]
Thanks!

It already is on Pypi: `pip install adb-shell`. I should add that to the README.
