### ISSUE TITLE
raw option to device::shell response

### ISSUE THREAD

**Issue by fnzr** [JeffLIrion/adb_shell#63]
Hi,
I'm using this library to take a screenshot with the command `/system/bin/screencap -p`. Currently, saving the screenshot fails because the shell function [always decodes adb's response](https://github.com/JeffLIrion/adb_shell/blob/master/adb_shell/adb_device.py#L384)

I made a small change to optionally skip the decoding part, the commit is [here](https://github.com/fnzr/adb_shell/commit/f627c17a39ab79bcb7ca7b0fee1c225e0c57a72c). All tests still pass, so this shouldn't be a breaking change.

To reproduce the current error, do something like:

```python
from adb_shell.adb_device import AdbDeviceTcp
device = AdbDeviceTcp(ip, port)
response = device.shell('/system/bin/screencap -p')
with open("out.png", "bw") as f:
    f.write(response)
```

This should throw a UnicodeDecodeError. With my change,  the only difference would be `response = device.shell('/system/bin/screencap -p', raw=True)`.

May I open a PR?

**Comment by JeffLIrion** [comment]
A pull request would be welcome! Could you please make the following changes:

1. Change `raw=False` to `decode=True`
2. Change the function to:

    ```python
    if decode:
        return b''.join(self._streaming_command(b'shell', command.encode('utf8'), adb_info)).decode('utf8')
    return b''.join(self._streaming_command(b'shell', command.encode('utf8'), adb_info))
    ```

3. Document the `decode` parameter in the same style as the other parameters
4. Add a unit test so that this is covered

Thanks!

**Comment by fnzr** [comment]
Alright, here's the [commit](https://github.com/fnzr/adb_shell/commit/dcdd0256e365cad156af1f7cf429a1e4c41764c9).

Is a test for each return type ok or do you prefer a single test?

**Comment by JeffLIrion** [comment]
I think one unit test (`test_shell_dont_decode`) is fine. I think you should check that the return is `b'PASS'`.

**Comment by fnzr** [comment]
[Updated](https://github.com/fnzr/adb_shell/commit/28002fc7944e5642999a9863623727e55265af07)

**Comment by JeffLIrion** [comment]
I think that looks good. You should create a pull request.

**Comment by fnzr** [comment]
Solved with successful merge. Great work on this package!
