### ISSUE TITLE
Root access

### ISSUE THREAD

**Issue by alonroth** [JeffLIrion/adb_shell#74]
First of all thanks for this awesome library - it was really nice to work with it so far!

I was wondering how can I "enter" to a root "mode", the equivalent of this simple shell command -
`adb root`

Is it possible to do it with this library? If not, could you please add this functionality?

Many thanks!

**Comment by JeffLIrion** [comment]
Thanks for the kind words!

That's not "officially" supported, but I took a look at [python-adb](https://github.com/google/python-adb/blob/0e507956dce7eca2e1e2fee066e9aa6a0a393f5a/adb/adb_commands.py#L355-L357) and I think you should be able to accomplish this via:

```python
from adb_shell.adb_device import AdbDeviceTcp, _AdbTransactionInfo

dev = AdbDeviceTcp(...)

# you could use timeout_s=None and total_timeout_s=10.0
adb_info = _AdbTransactionInfo(None, None, timeout_s, total_timeout_s)

dev._streaming_command(b'root', b'', adb_info)
```

Please let me know if that works.

**Comment by alonroth** [comment]
Interesting.. Thanks for your quick response.. I'll try it and let you know.

Thanks!

**Comment by alonroth** [comment]
Unfortunately, it's not quite working..
The command itself maybe works but the reason I'm trying to enter the "root mode" is so I could pull data from the "/data/data" path which is only available via root.

Trying to do the following:

```
adb = AdbDeviceTcp(...)
adb_info = _AdbTransactionInfo(None, None, 10, 10)
b = adb._streaming_command(b'root', b'', adb_info)
response = adb.shell('ls -l /data/data')
```

still resolved in `ls: /data/data: Permission denied` as before

**Comment by JeffLIrion** [comment]
Try

```python
# same as above, and then
b''.join(adb._streaming_command(b'root', b'', adb_info))
```

What is the output of that?

Also, are you able to get root access using the official adb binary?

**Comment by JeffLIrion** [comment]
@alonroth have you had a chance to try

```python
# same as above, and then
b''.join(adb._streaming_command(b'root', b'', adb_info))
```

And are you able to get root access using the ADB binary?

**Comment by alonroth** [comment]
Hi @JeffLIrion 

Sorry for the delay I've been sick for the last couple of days..

I tried the following and it didn't work.:
`b''.join(adb._streaming_command(b'root', b'', adb_info))`

When I try the offical adb library it kind of works:
`adb_commands.Root()`

After running this command, I see it's been switched to root when I run on my CLI:
`adb shell whoami`

Although, I get this exception on my app:
`ConnectionResetError: [Errno 54] Connection reset by peer`

Currently, I have a workaround to make it work - I use the offical library in order to move to root mode and I catch the above exception so I could continue working with the ADB.

What do you think?

**Comment by JeffLIrion** [comment]
How did you check that `b''.join(adb._streaming_command(b'root', b'', adb_info))` didn't work? Was there any output from that command?

**Comment by JeffLIrion** [comment]
The command above that you ran using `adb-shell` is exactly equivalent to the `adb_commands.Root()` command in the `adb` package, so I don't understand why one would work but not the other. 

When you connect via CLI (i.e., using the ADB binary), I think that will break the connection established by the `adb` and/or `adb-shell` packages. I think that's what caused the `ConnectionResetError` that you got. Furthermore, I'm not sure that running `adb shell whoami` via CLI is a valid check that the command run by the `adb` / `adb-shell` Python package actually got you root access; you should be able to run `dev.shell("whoami")` in `adb-shell` or `dev.Shell("whoami")` in `adb` to check this. 

If you really want to know what's going on in `adb-shell`, do

```python

import logging

logging.getLogger().setLevel(logging.DEBUG)

# run the adb-shell commands from above
```

**Comment by JeffLIrion** [comment]
For reference:

#### `adb`

* [`Root()`](https://github.com/google/python-adb/blob/f4e597fe55900651a8a91fccc1e09061fd96b5e9/adb/adb_commands.py#L355)
* [`Command()`](https://github.com/google/python-adb/blob/f4e597fe55900651a8a91fccc1e09061fd96b5e9/adb/adb_protocol.py#L391)
* [`StreamingCommand()`](https://github.com/google/python-adb/blob/f4e597fe55900651a8a91fccc1e09061fd96b5e9/adb/adb_protocol.py#L414)


#### `adb-shell`

* [`_streaming_command()`](https://github.com/JeffLIrion/adb_shell/blob/da9ffba39361b6c25b137d7558bfc16bf59b40ae/adb_shell/adb_device.py#L926)

**Comment by JeffLIrion** [comment]
Any updates on this?

**Comment by alonroth** [comment]
I agree, I saw that it's quite the same thing as well, I don't understand either why one works and the other doesn't... I just keep using both of the libraries :)

**Comment by JeffLIrion** [comment]
I pushed out a new release.  If you install it via `pip install --upgrade adb-shell`, you can try to gain root access via:

```python
import logging
logging.getLogger().setLevel(logging.DEBUG)  # show debugging log info

dev = AdbDeviceTcp(...)  # fill in the arguments here
dev._service(b'root', b'')
```

**Comment by alonroth** [comment]
Interesting, I'll try and keep you posted

**Comment by alonroth** [comment]
@JeffLIrion 

Not working for me... :|

```
  File "ADB.py", line 20, in __init__
    dev._service(b'root', b'')
  File "server/env/lib/python3.7/site-packages/adb_shell/adb_device.py", line 404, in _service
    return b''.join(self._streaming_command(service, command, adb_info)).decode('utf8')
  File "server/env/lib/python3.7/site-packages/adb_shell/adb_device.py", line 1011, in _streaming_command
    self._open(b'%s:%s' % (service, command), adb_info)
  File "server/env/lib/python3.7/site-packages/adb_shell/adb_device.py", line 795, in _open
    self._send(msg, adb_info)
  File "server/env/lib/python3.7/site-packages/adb_shell/adb_device.py", line 980, in _send
    self._handle.bulk_write(msg.pack(), adb_info.timeout_s)
  File "server/env/lib/python3.7/site-packages/adb_shell/handle/tcp_handle.py", line 151, in bulk_write
    _, writeable, _ = select.select([], [self._connection], [], timeout)
TypeError: argument must be an int, or have a fileno() method.
```

**Comment by JeffLIrion** [comment]
I forgot: you have to connect to the device. 

```python
import os

from adb_shell.adb_device import AdbDeviceTcp
from adb_shell.auth.sign_pythonrsa import PythonRSASigner

import logging
logging.getLogger().setLevel(logging.DEBUG)  # show debugging log info

with open(os.path.expanduser('~/.android/adbkey')) as f:  # update the path to the key file accordingly
    priv = f.read()
signer = PythonRSASigner('', priv)

dev = AdbDeviceTcp('192.168.0.222', 5555, default_timeout_s=9.)
dev.connect(rsa_keys=[signer], auth_timeout_s=0.1)

dev._service(b'root', b'')
```

**Comment by JeffLIrion** [comment]
@alonroth have you tried using the latest code that I posted?

**Comment by JeffLIrion** [comment]
> ```python
> import os
> 
> from adb_shell.adb_device import AdbDeviceTcp
> from adb_shell.auth.sign_pythonrsa import PythonRSASigner
> 
> import logging
> logging.getLogger().setLevel(logging.DEBUG)  # show debugging log info
> 
> with open(os.path.expanduser('~/.android/adbkey')) as f:  # update the path to the key file accordingly
>     priv = f.read()
> signer = PythonRSASigner('', priv)
> 
> dev = AdbDeviceTcp('192.168.0.222', 5555, default_timeout_s=9.)
> dev.connect(rsa_keys=[signer], auth_timeout_s=0.1)
> 
> dev._service(b'root', b'')
> print(dev.shell('whoami'))
> ```

@Halastra or @matthieuxyz, can either of you confirm that the above code snippet successfully gets root access? You'll need to be running version 0.1.2 of `adb-shell` or newer.

**Comment by Halastra** [comment]
I don't have a rooted device at the moment. Sorry.

**Comment by matthieuxyz** [comment]
Neither do I, sorry.

**Comment by dark-lbp** [comment]
Test with current master branch.
Device_Info: Android 6.0.1

```python
import os

from adb_shell.adb_device import AdbDeviceTcp
from adb_shell.auth.sign_pythonrsa import PythonRSASigner

import logging
logging.getLogger().setLevel(logging.DEBUG)  # show debugging log info

with open(os.path.expanduser('~/.android/adbkey')) as f:  # update the path to the key file accordingly
    priv = f.read()
signer = PythonRSASigner('', priv)

dev = AdbDeviceTcp('x.x.x.x', 5555, default_timeout_s=9.)
dev.connect(rsa_keys=[signer], auth_timeout_s=0.1)

dev._service(b'root', b'')
print("dev.shell('whoami'): {}".format(dev.shell('whoami')))
>>> dev.shell('id'): uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats) context=u:r:shell:s0
```

**Comment by JeffLIrion** [comment]
@dark-lbp thanks for testing! I'll add a `root` method and close out this issue.

**Comment by JeffLIrion** [comment]
Closed via https://github.com/JeffLIrion/adb_shell/pull/92
