### ISSUE TITLE
The timeout mechanism does not working

### ISSUE THREAD

**Issue by kunzhipeng** [JeffLIrion/adb_shell#86]
Following code will stuck all the time:
`print device1.shell('busybox ping www.baidu.com', timeout_s=10, total_timeout_s=10.)`

**Comment by JeffLIrion** [comment]
Please use the issue template and post a debug log. 

I think the problem is that the command you're running never finishes. Try this:

```python3
generator = device1.streaming_shell('busybox ping www.baidu.com', timeout_s=10, total_timeout_s=10.)

print(next(generator))
```

**Comment by JeffLIrion** [comment]
> I think the problem is that the command you're running never finishes. Try this:
> 
> ```python
> generator = device1.streaming_shell('busybox ping www.baidu.com', timeout_s=10, total_timeout_s=10.)
> 
> print(next(generator))
> ```

Yep, that was it: your command never finishes. The timeout works. To test it, specify a timeout of, say, 5 seconds and send a command `sleep 7 && echo hello`. That will fail.
